### ISSUE TITLE
Cannot adjust fee - Fee information in the system does not match the fee information in STAR

### ISSUE THREAD

**Issue by topski2000** [programmers-analysts-test/tickets#150]
Avon Cosmetics, Inc. (AVO387-185) Php180,000
Fox International Channel Philippines Corporation (FOX716-149) Php120,000
FRESENIUS - Asia Renal Care (Philippines), Inc. (ASI768-946)   Php75,000

reported by Janis Maghinay

**Comment by vbramos** [comment]
Duplicate ticket with #51.  We already performed a data correction to project affected by the bug.
