### ISSUE TITLE
Change the first sentence in the "About us" at the bottom of the homepage to "Punongbayan & Araullo (P&A) is the Philippine member firm within Grant Thornton International Ltd, one of the world's leading organizations of independently owned and managed accounting and consulting firms."

### ISSUE THREAD

**Issue by topski2000** [programmers-analysts-test/tickets#209]
Change the first sentence in the "About us" at the bottom of the homepage to "Punongbayan & Araullo (P&A) is the Philippine member firm within Grant Thornton International Ltd, one of the world's leading organizations of independently owned and managed accounting and consulting firms."

**Comment by leonardduque** [comment]
Done
