### ISSUE TITLE
Add new image in the carousel

### ISSUE THREAD

**Issue by topski2000** [programmers-analysts-test/tickets#214]
Grant Thornton named 'Employer of the Year' by International Accounting Bulletin, for the second consecutive year
![winner2015](https://cloud.githubusercontent.com/assets/12163624/10442510/7d88e298-7185-11e5-8308-bb1eaa01b72a.png)

Grant Thornton has been awarded 'Employer of the year'  at the reputable International Accounting Bulletin (IAB) awards ceremony, a global magazine covering the professional services world.

For the second consecutive year, Grant Thornton was thrilled to win title at the IAB awards. The judges recognised the hugely successful Global Jam which attributed to the award.

**Comment by leonardduque** [comment]
Done
