### ISSUE TITLE
Rename SSS Loan and HDMF Loan

### ISSUE THREAD

**Issue by topski2000** [programmers-analysts-test/tickets#254]
Please rename the following certificate types in the Certification facility of the e-Payroll:
1.  from SSS LOAN to SSS SALARY LOAN
2. from HDMF LOAN to HDMF SALARY LOAN

![epayroll-certificate rename](https://cloud.githubusercontent.com/assets/12163624/11519514/d93cd7ee-98d5-11e5-9a01-5f55b91ccca3.png)

**Comment by jobocsh** [comment]
done
